Import("env")

source=Split("model.c gsl_vector_helpers.c ccd.c arnie.c")
headers=Split("model.h gsl_vector_helpers.h ccd.h arnie_params.h arnie.h")
target="#/lib/robot_model"

env.Install(source=headers, target="#/include/robot_model")
env.Library(source=source, target=target)
