Import("env")

source=Split("ftdi.c")
headers=Split("ftdi.h")
docs=Split("AUTHORS  COPYING.LIB  ChangeLog  README")
target="#/lib/ftdi"

env.Library(source=source, target=target)
env.Install(source=headers, target="#/include/ftdi")
env.Install(source=docs, target="#/doc/ftdi")